### ISSUE TITLE
[Deployment]: Fleet & APM configuration failed on deploying 8.1 Snapshot.

### ISSUE THREAD

**Issue by amolnater-qasource** [elastic/fleet-server#1082]
**Description:**
`APM & Fleet configuration failed` while creating 8.1 Snapshot environment from:
- https://staging.found.no/deployments/create

**Platform:**
Google Cloud Platform

**Observations:**
- Build is Healthy with Warnings
- Unable to load Fleet tab.

**Screenshot:**
![3](https://user-images.githubusercontent.com/77374876/149081468-e4c9c3b0-6a99-4082-9a86-51dc6d093c1a.JPG)
![4](https://user-images.githubusercontent.com/77374876/149081475-ed2e2c09-7b55-452c-871d-825c5893cea5.JPG)

**Note:**
This issue is not observed for 7.16.3 and 8.0-Snapshot.

**Comment by amolnater-qasource** [comment]
@manishgupta-qasource Please review.

**Comment by manishgupta-qasource** [comment]
Reviewed & mention to @jlind23

**Comment by jlind23** [comment]
Thanks for the ping!
@jen-huang it rather seems to be a fleet issue am i wrong?

**Comment by jlind23** [comment]
Hello @amolnater-qasource @manishgupta-qasource it seems to be the issue mentioned here:
https://github.com/elastic/beats/issues/29811

A change on Elasticsearch side has caused it.

cc @ruflin @ph

**Comment by jen-huang** [comment]
Yep, caused by an ES change. We fixed it in #122798 so should be available in the next snapshot.

**Comment by amolnater-qasource** [comment]
Hi @jen-huang 
We are still not able to deploy Healthy 8.1-Snapshot from any of the below platforms:
- https://staging.found.no/
- https://console.qa.cld.elstc.co/

**Screenshots:**
![12](https://user-images.githubusercontent.com/77374876/149871199-8582c61a-9209-42cf-8a63-112a0b7a4926.JPG)
![13](https://user-images.githubusercontent.com/77374876/149871202-c35d5ae5-1372-4bf5-b932-11314f6a3f51.JPG)

Hence we are **re-opening** this issue.
cc: @jlind23 

Thanks

**Comment by amolnater-qasource** [comment]
Further @jlind23 
We are unable to upgrade from 7.17.0 Snapshot>8.0 Snapshot as we are not getting the 8.0 version available for upgrade from both platforms.
![14](https://user-images.githubusercontent.com/77374876/149874449-315fdde3-1094-4d6b-96a8-e69c0107a2d2.JPG)

Please let us know if you want us to log separate issue for this.
Thanks

**Comment by jlind23** [comment]
@ph @ruflin do you know when a 8.1 will be available?

**Comment by amolnater-qasource** [comment]
Hi @jlind23 
We are successfully able to deploy `Healthy` 8.1 Snapshot with complete configuration from:
- https://staging.found.no/

**Screenshot:**
![4](https://user-images.githubusercontent.com/77374876/150912784-838d3eaf-c3ec-4c3e-a40a-1ec27d96abb6.JPG)

Hence we are **closing** this issue.
Thanks
