### ISSUE TITLE
[Self-Managed]: Fleet server gets unhealthy on installation on self-managed environment.

### ISSUE THREAD

**Issue by amolnater-qasource** [elastic/fleet-server#2083]
**Kibana version:**  8.6 Snapshot self-managed environment

**Host OS and Browser version:** Windows, All

**Build details:**
```
VERSION: 8.6.0 Snapshot Kibana self-managed environment
BUILD: 58242
COMMIT: 2e04dac8367f95a986ed0ee32fd030bb3f6d5d0f
```

**Preconditions:**
1. 8.6 Snapshot self-managed environment should be available.
2. Fleet server policy should be created having fleet server integration.

**Steps to reproduce:**
1. Install fleet-server using Fleet server policy.
2. Observe agent gets unhealthy.

**Expected Result:**
Fleet server should remain healthy on self-managed environment.

**Screenshots:**
![3](https://user-images.githubusercontent.com/77374876/201854886-d4dd1e42-3971-4622-b25c-b468ce516034.JPG)
![4](https://user-images.githubusercontent.com/77374876/201854894-05ea3fcf-2198-4e5e-9717-49aa08a55fea.JPG)

**Agent Logs:**
[logs.zip](https://github.com/elastic/fleet-server/files/10010204/logs.zip)

**Elastic-agent.yml:**
[elastic-agent.zip](https://github.com/elastic/fleet-server/files/10010209/elastic-agent.zip)

**Comment by amolnater-qasource** [comment]
@karanbirsingh-qasource Please review.

**Comment by karanbirsingh-qasource** [comment]
Secondary review for this ticket is Done

**Comment by cmacknz** [comment]
I see this in the logs that is probably causing this problem:

```json
{"log.level":"info","@timestamp":"2022-11-15T06:27:39.281Z","log.origin":{"file.name":"coordinator/coordinator.go","file.line":325},"message":"Existing component state changed","component":{"id":"fleet-server-default","state":"Healthy","message":"Healthy: communicating with pid '7912'","inputs":[{"id":"fleet-server-default-fleet-server","state":"Degraded","message":"Running on policy with Fleet Server integration: fleet-server-policy; missing config fleet.agent.id (expected during bootstrap process)"}],"output":{"id":"fleet-server-default","state":"Degraded","message":"Running on policy with Fleet Server integration: fleet-server-policy; missing config fleet.agent.id (expected during bootstrap process)"}},"ecs.version":"1.6.0"}
```

Specifically `"Running on policy with Fleet Server integration: fleet-server-policy; missing config fleet.agent.id (expected during bootstrap process)"` seems to be the problem.

@michel-laterman any ideas what might be missing here?

**Comment by michel-laterman** [comment]
The most recent logs output by the agent in the log bundle indicate a recovery:
```
{"log.level":"info","@timestamp":"2022-11-15T06:28:04.382Z","log.origin":{"file.name":"coordinator/coordinator.go","file.line":325},"message":"Existing component state changed","component":{"id":"fleet-server-default","state":"Healthy","message":"Healthy: communicating with pid '8044'","inputs":[{"id":"fleet-server-default-fleet-server-fleet_server-3406bdd3-e60d-46d0-b168-1c3b9341af80","state":"Healthy","message":"Running on policy with Fleet Server integration: fleet-server-policy"}],"output":{"id":"fleet-server-default","state":"Healthy","message":"Running on policy with Fleet Server integration: fleet-server-policy"}},"ecs.version":"1.6.0"}
```

**Comment by kevinlog** [comment]
@amolnater-qasource

Since we reverified [this ticket](https://github.com/elastic/kibana/issues/145202) about an unhealthy Endpoint and Fleet Server, does it follow that we can also close this ticket?  I think it may have been the same root cause.

**Comment by amolnater-qasource** [comment]
Hi @kevinlog 

We have revalidated this on latest 8.6 SNAPSHOT and found that the issue is **still reproducible**.

**Observations:**
- Installed fleet server gets unhealthy on installation with Fleet Server policy having System and Fleet Server integration.

**Build details:**
BUILD: 58247
COMMIT: f893523d63e99d623269969af3f611ddff36c1c1

**Agent details:**
![image](https://user-images.githubusercontent.com/77374876/202187388-9edeb5f6-188e-4b1f-bc53-ccbb6449554b.png)

**Screenshot:**
![image](https://user-images.githubusercontent.com/77374876/202187623-f303140a-e4b1-4833-8279-05ae29193d18.png)

![image](https://user-images.githubusercontent.com/77374876/202187898-a4e2ce51-502c-4e5a-b154-dad649deb796.png)


Please let us know if anything else is required from our end.
Thanks

**Comment by cmacknz** [comment]
Thanks this appears to be intermittent. @amolnater-qasource does fleet-server eventually recover to a healthy state as we observed previously?

**Comment by michel-laterman** [comment]
Can you provide a diagnostics bundle from the failing instance?

**Comment by amolnater-qasource** [comment]
Hi @cmacknz @michel-laterman 
We have revalidated this issue on latest 8.6.0 BC1 self-managed kibana environment and had below observations:

- Fleet server policy is created with Fleet Server and System integration.
- Fleet Server is installed with the above created fleet server policy integration
- **Fleet Server is unhealthy when Fleet Server policy has the System integration.**
- **On removing System integration from Fleet Server policy, fleet-server gets back to Healthy state.**

**Screenshots:**
![7](https://user-images.githubusercontent.com/77374876/202654237-80909dbb-30c8-447e-b551-6707c4b75637.JPG)

![14](https://user-images.githubusercontent.com/77374876/202660041-2c9e9c93-1bd8-4a68-85ec-f95358b05922.JPG)


![9](https://user-images.githubusercontent.com/77374876/202654227-9d0e8e61-0311-44c1-bbc6-426ff7ab7ccf.JPG)

**Logs:**
- Collecting agent logs through diagnostics command is blocked due to reported issue: https://github.com/elastic/elastic-agent/issues/1715
 
![8](https://user-images.githubusercontent.com/77374876/202654590-c0e90c23-6db9-49a6-8d40-75f8d9aad96f.JPG)

**Agent Logs:**
[logs.zip](https://github.com/elastic/fleet-server/files/10039456/logs.zip)

**elastic-agent.yml:**
[elastic-agent.zip](https://github.com/elastic/fleet-server/files/10039458/elastic-agent.zip)

**Build details:**
VERSION: 8.6.0
BUILD: 58392
COMMIT: 50a7feb0a5eb068d3acccc49c83b9ccb6db6734f

Please let us know if anything else is required from our end.
Thanks

**Comment by joshdover** [comment]
> Specifically `"Running on policy with Fleet Server integration: fleet-server-policy; missing config fleet.agent.id (expected during bootstrap process)"` seems to be the problem.

This is actually "normal" and it confuses us and support on a regular basis. You'll see this on every boot of Fleet Server on Cloud, for instance.

We should fix this log by either removing it or getting ID in there correctly. Maybe the log just needs to be moved to a later part of the flow. @michel-laterman could you take a quick look at that? If it's more than an hour or so we can file a follow up issue.

**Comment by michel-laterman** [comment]
Has the agent been installed as admin/root?

**Comment by michel-laterman** [comment]
> We should fix this log by either removing it or getting ID in there correctly. Maybe the log just needs to be moved to a later part of the flow. @michel-laterman could you take a quick look at that? If it's more than an hour or so we can file a follow up issue.

The ID is missing as part of the bootstrap. I don't think we want to loose the message entirely. And we are unable to (easily) just set that one message to debug. But we can set all state change messages that the fleet-server logs to debug

**Comment by jlind23** [comment]
@amolnater-qasource were you able to test this again since we merged a lot of V2 fixes?

**Comment by amolnater-qasource** [comment]
Hi @jlind23 

We have revalidated this issue on latest 8.6 BC5 kibana self-managed environment and found this issue **still reproducible**.

**Observations:**
- Fleet Server is unhealthy when Fleet Server policy has the System integration.
- On removing System integration from Fleet Server policy, fleet-server gets back to Healthy state.

**Build details:**
BUILD: 58693
COMMIT: ed40c16ce9999cc47ad55c11bb097d2e443b31a6

**Screenshot:**
![9](https://user-images.githubusercontent.com/77374876/205852908-8f1dc8ec-e12b-4daa-817b-418152cff62a.JPG)
![10](https://user-images.githubusercontent.com/77374876/205852900-394ad7f6-c801-4348-af1e-9174c163e591.JPG)

**Logs:**
[[Unhealthy]elastic-agent-diagnostics-2022-12-05T13-48-21Z-00.zip](https://github.com/elastic/fleet-server/files/10163957/Unhealthy.elastic-agent-diagnostics-2022-12-05T13-48-21Z-00.zip)

Please let us know if anything else is required from our end.
Thanks

**Comment by joshdover** [comment]
@cmacknz @blakerouse @michalpristas any ideas on this one? Feels like another potential 8.6 blocker, but maybe it overlaps with another issue we're already working on.

**Comment by michalpristas** [comment]
in logs i see this which is suspicious
```
Error reloading input: 3 errors: Error creating runner from config: No paths were defined for input accessing config; Error creating runner from config: No paths were defined for input accessing config; Error creating runner from config: No paths were defined for input accessing config
```

complaining about no paths being provided, this is about to get fixed

**Comment by cmacknz** [comment]
Yes, the fix for that is https://github.com/elastic/beats/pull/33921.

**Comment by jlind23** [comment]
@amolnater-qasource could you please test this out again as the new BC is available?

**Comment by amolnater-qasource** [comment]
Sure @jlind23, we will retest this issue once next BC is available.

Thank You!

**Comment by amolnater-qasource** [comment]
Hi @jlind23 
We have revalidated this issue on latest 8.6 BC6 kibana self-managed environment and observed this issue is **fixed now**.

**Observations:**
- Fleet server remains healthy on self-managed environment with policy having policy having fleet-server and system integration.

**Build details:**
8.6 BC6 Kibana cloud environment
BUILD: 58740
COMMIT: f329a77595950244361736dff7208a810299fd69

**Screenshots:**
![3](https://user-images.githubusercontent.com/77374876/206394878-a6e44a3d-9eac-426c-abdc-8a13795d2d02.JPG)

**Logs:**
[elastic-agent-diagnostics-2022-12-08T05-49-00Z-00.zip](https://github.com/elastic/fleet-server/files/10183460/elastic-agent-diagnostics-2022-12-08T05-49-00Z-00.zip)

Hence we are **closing this issue** and marking this issue as **QA:Validated**.

Thanks

**Comment by prachigupta-qasource** [comment]
### `Bug Conversion`

- Test-Case not required as this particular checkpoint is already covered in the following testcase:
   - https://elastic.testrail.io/index.php?/cases/view/77071
 
Thanks!
