### ISSUE TITLE
[Self-managed]: Unable to install Fleet Server agent on 7.14.0.

### ISSUE THREAD

**Issue by amolnater-qasource** [elastic/fleet-server#503]
**Kibana version:** 7.14.0 Snapshot Kibana self-managed environment

**Host OS and Browser version:** Windows, All

**Build details:**
```
Build: 42157
Commit: dcacd04872050ff322f7e9bb36af913e40d5977e
Artifact Link:
https://snapshots.elastic.co/7.14.0-c5e16e4e/downloads/beats/elastic-agent/elastic-agent-7.14.0-SNAPSHOT-windows-x86_64.zip
```

**Preconditions:**
1. 7.14.0 Snapshot Kibana self-managed environment should be available.
2. Test Signing should be ON.

**Steps to reproduce:**
1. Login to Kibana environment.
2. Navigate to Agents tab and copy install command for Fleet Server.
3. Run install command and observe 

**Expected Result:**
Fleet Server agent must be installed on running install command on self managed 7.14.0 Snapshot Kibana.

**Screenshot:**
![3](https://user-images.githubusercontent.com/77374876/123917926-f7c7e700-d9a0-11eb-992e-6d81297fdc70.JPG)

**Comment by amolnater-qasource** [comment]
@manishgupta-qasource Please review

**Comment by manishgupta-qasource** [comment]
Reviewed & Assigned to @EricDavisX

**Comment by EricDavisX** [comment]
I believe this is a duplicate to the Beats ticket put in:
https://github.com/elastic/beats/issues/26588

because, as Blake notes there that it was reproducible in a 'local' environment.  He cites too that a refactor was underway and this *may be fixed already.  we can close this out when we see it fixed.

**Comment by andresrc** [comment]
We have just merged a PR that can be a fix for this, can you retest this one? Thanks! (we'll need another snapshot or BC2), see https://github.com/elastic/dev/issues/1707#issuecomment-875696846

**Comment by amolnater-qasource** [comment]
Hi @EricDavisX
We have revalidated this issue on 7.14.0 self-managed BC-2 environment and found it **still reproducible**.
- We are still not able to install Fleet Server agent

**Screenshot:**
![16](https://user-images.githubusercontent.com/77374876/124908741-46136080-e007-11eb-8891-999364c808d4.JPG)

**Build details:**
```
Build: 42367
Commit: d417b7aaba7d337fd45da08ed75dcc2c7fdf56cb
Artifact Link: https://staging.elastic.co/7.14.0-ce834ac2/summary-7.14.0.html
``
@andresrc Could you please confirm if using the quick-start mode of security we are supposed to install the agent on self-managed environment?

For now we are not able to install agent with either of the modes.

Thanks
QAS

**Comment by amolnater-qasource** [comment]
Hi @EricDavisX
We have revalidated this issue on 7.14.0 self-managed BC-2 environment and found it **still reproducible**.
- We are still not able to install Fleet Server agent

**Screenshot:**
![16](https://user-images.githubusercontent.com/77374876/124908741-46136080-e007-11eb-8891-999364c808d4.JPG)

**Build details:**
```
Build: 42367
Commit: d417b7aaba7d337fd45da08ed75dcc2c7fdf56cb
Artifact Link: https://staging.elastic.co/7.14.0-ce834ac2/summary-7.14.0.html
```

@andresrc Could you please confirm if using the quick-start mode of security we are supposed to install the agent on self-managed environment?

For now we are not able to install agent with either of the modes.

Thanks
QAS

**Comment by andresrc** [comment]
@blakerouse can you take a look to this one? Thanks
